### ISSUE TITLE
Kurze Frage ;)

### ISSUE THREAD

**Issue by kingozorg** [rueetschli/OpenAI-GPT-3.5-turbo-simple-script#1]
Moin! Kurze Frage: Wie/Wo müsste man die SYSTEM Anweisung im script einfügen? Finde/Kann das leider nicht. Schöne Grüße! 

So was z.B.:

                'messages' => array(
                    array(
                        'role' => 'system',
                        'content' => $system
                    ),
                    array(
                        'role' => 'user',
                        'content' => $message
                    )

**Comment by rueetschli** [comment]
Hej,
Was möchtest du denn machen? 

Im Script werden der Assistent und der Benutzer wie folgt unterschieden:

```

if( !empty( $context ) ) {
    $context = array_slice( $context, -5 );
    foreach( $context as $message ) {
        $postData['messages'][] = ['role' => 'user', 'content' => str_replace("\n", "\\n", $message[0])];
        $postData['messages'][] = ['role' => 'assistant', 'content' => str_replace("\n", "\\n", $message[1])];
    }
}

```

Hilft das?
Lg

**Comment by rueetschli** [comment]
Hey, ja das geht.
Dafür findest du in der Zeile 8 von message.php diesen Eintrag:

`"messages" => [],`

Ersetze diesen mit so etwas:
```
"messages" => [
        [
            "role" => "system",
            "content" => "Hey, können wir dieses Mal ohne Sarkasmus reden?"
        ]
    ],
```
